#!/usr/bin/env bash
# Provisions a new Raspberry Pi device credential for the Jarvis
# home-automation backend, without ever embedding secrets in this script or
# in source control.
#
# Generates a cryptographically random device ID and device token locally,
# stores only a SHA-256 hash of the high-entropy token (never the token itself) in
# the backend's "Devices" Azure Table, and prints the plaintext token once so
# the operator can copy it into the Pi's /etc/home-assistant-pi/config.env.
#
# This script performs infrastructure-adjacent data provisioning only. It
# does not install or configure anything on the Raspberry Pi itself -- see
# pi-client/scripts/install.sh for that.
#
# Requires the caller to be authenticated via `az login` and to hold the
# "Storage Table Data Contributor" role (or higher) on the target storage
# account, since data-plane access uses Azure AD (--auth-mode login) rather
# than a shared key.
#
# Usage:
#   ./provision-device.sh --device-name kitchen-pi \
#       --storage-account stjarvisdevabc123
#
# Options:
#   -n, --device-name       Human-readable device name/label. Required.
#   -a, --storage-account   Storage account name (infra output `storageAccountName`). Required.
#   -t, --table-name        Azure Table name holding device records. Defaults to "Devices".
#   -o, --output-file       Optional path to write a config.env snippet with the plaintext token.
#   -h, --help              Show this help text.

set -euo pipefail

DEVICE_NAME=""
STORAGE_ACCOUNT=""
TABLE_NAME="Devices"
OUTPUT_FILE=""

print_help() {
    sed -n '2,29p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -n|--device-name)
            DEVICE_NAME="$2"; shift 2 ;;
        -a|--storage-account)
            STORAGE_ACCOUNT="$2"; shift 2 ;;
        -t|--table-name)
            TABLE_NAME="$2"; shift 2 ;;
        -o|--output-file)
            OUTPUT_FILE="$2"; shift 2 ;;
        -h|--help)
            print_help; exit 0 ;;
        *)
            echo "Unknown option: $1" >&2
            print_help
            exit 1 ;;
    esac
done

if [[ -z "$DEVICE_NAME" || -z "$STORAGE_ACCOUNT" ]]; then
    echo "Error: --device-name and --storage-account are required." >&2
    print_help
    exit 1
fi

if ! [[ "$DEVICE_NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]{1,63}$ ]]; then
    echo "Error: device name must be alphanumeric with hyphens/underscores, 2-64 chars." >&2
    exit 1
fi

if ! command -v az >/dev/null 2>&1; then
    echo "Error: Azure CLI (az) is required but was not found on PATH." >&2
    echo "Install it from https://learn.microsoft.com/cli/azure/install-azure-cli" >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "Error: openssl is required to generate a cryptographically random token but was not found on PATH." >&2
    exit 1
fi

# --- Generate credentials locally; nothing here is ever written to source control. ---
if command -v uuidgen >/dev/null 2>&1; then
    DEVICE_ID=$(uuidgen | tr '[:upper:]' '[:lower:]')
else
    DEVICE_ID=$(python3 -c 'import uuid; print(uuid.uuid4())')
fi

DEVICE_TOKEN=$(openssl rand -base64 32 | tr -d '=\n' | tr '+/' '-_')
TOKEN_HASH=$(printf '%s' "$DEVICE_TOKEN" | openssl dgst -sha256 -hex | awk '{print $NF}')
CREATED_AT_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)

echo "Provisioning device '$DEVICE_NAME'..."
echo "Device ID : $DEVICE_ID"

echo "Writing device record (hash only) to table '$TABLE_NAME' in storage account '$STORAGE_ACCOUNT'..."

# Persist only the hash, via Azure AD data-plane auth (no storage key used).
if ! az storage entity insert \
    --auth-mode login \
    --account-name "$STORAGE_ACCOUNT" \
    --table-name "$TABLE_NAME" \
    --entity \
        "PartitionKey=device" \
        "RowKey=$DEVICE_ID" \
        "DeviceName=$DEVICE_NAME" \
        "TokenHash=$TOKEN_HASH" \
        "Enabled=true" \
        "CreatedAtUtc=$CREATED_AT_UTC" \
    --if-exists fail \
    --output none; then
    echo "Error: failed to write the device record. Confirm the table exists (created by infra/main.bicep) and that you hold the Storage Table Data Contributor role on the storage account." >&2
    exit 1
fi

echo
echo "Device record created."
echo
echo "==================== DEVICE CREDENTIALS (shown once) ===================="
echo "HAP_DEVICE_ID=$DEVICE_ID"
echo "HAP_DEVICE_TOKEN=$DEVICE_TOKEN"
echo "==========================================================================="
echo "Copy these lines into the Pi's /etc/home-assistant-pi/config.env now."
echo "This token is never stored in plaintext server-side; only its hash is kept. There is no way to retrieve it again -- re-run this script to issue a new credential if it is lost."

if [[ -n "$OUTPUT_FILE" ]]; then
    umask 077
    cat > "$OUTPUT_FILE" <<EOF
# Generated by infra/scripts/provision-device.sh on $CREATED_AT_UTC
# SECURITY: This file contains a plaintext device credential.
# Copy its contents to the Pi's /etc/home-assistant-pi/config.env, then
# delete this local file. Never commit this file to source control.
HAP_DEVICE_ID=$DEVICE_ID
HAP_DEVICE_TOKEN=$DEVICE_TOKEN
EOF
    chmod 600 "$OUTPUT_FILE"
    echo
    echo "Credential also written to: $OUTPUT_FILE (owner-only permissions, 600)."
    echo "Delete this file from this machine once it has been securely transferred to the Pi."
fi
