#Requires -Version 7.0
<#
.SYNOPSIS
    Provisions a new Raspberry Pi device credential for the Jarvis
    home-automation backend, without ever embedding secrets in this script or
    in source control.

.DESCRIPTION
    Generates a cryptographically random device ID and device token locally,
    stores only a SHA-256 hash of the high-entropy token (never the token itself)
    in the backend's "Devices" Azure Table, and prints the plaintext token
    once so the operator can copy it into the Pi's /etc/home-assistant-pi/config.env.

    This script performs infrastructure-adjacent data provisioning only. It
    does not install or configure anything on the Raspberry Pi itself -- see
    pi-client/scripts/install.sh for that.

    Requires the caller to be authenticated via `az login` and to hold the
    "Storage Table Data Contributor" role (or higher) on the target storage
    account, since data-plane access uses Azure AD (--auth-mode login) rather
    than a shared key.

.PARAMETER DeviceName
    Human-readable device name/label (e.g. "kitchen-pi").

.PARAMETER StorageAccountName
    Storage account name to write the device record into (see infra deployment output `storageAccountName`).

.PARAMETER TableName
    Azure Table name holding device records. Defaults to "Devices".

.PARAMETER OutputFile
    Optional path to write a config.env snippet containing the plaintext
    token. If provided, the file is created with owner-only permissions and
    the operator is warned to move/secure it and delete it from this
    machine once transferred to the Pi. If omitted, the token is only
    printed to the console.

.EXAMPLE
    ./provision-device.ps1 -DeviceName kitchen-pi -StorageAccountName stjarvisdevabc123
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[a-zA-Z0-9][a-zA-Z0-9_-]{1,63}$')]
    [string]$DeviceName,

    [Parameter(Mandatory = $true)]
    [string]$StorageAccountName,

    [Parameter()]
    [string]$TableName = 'Devices',

    [Parameter()]
    [string]$OutputFile
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    Write-Error 'Azure CLI (az) is required but was not found on PATH. Install it from https://learn.microsoft.com/cli/azure/install-azure-cli'
    exit 1
}

# --- Generate credentials locally; nothing here is ever written to source control. ---
$deviceId = [guid]::NewGuid().ToString()

$tokenBytes = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Fill($tokenBytes)
$deviceToken = [Convert]::ToBase64String($tokenBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')

$sha256 = [System.Security.Cryptography.SHA256]::Create()
try {
    $hashBytes = $sha256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($deviceToken))
    $tokenHash = ([System.BitConverter]::ToString($hashBytes)).Replace('-', '').ToLowerInvariant()
}
finally {
    $sha256.Dispose()
}

$createdAtUtc = (Get-Date).ToUniversalTime().ToString('o')

Write-Host "Provisioning device '$DeviceName'..." -ForegroundColor Cyan
Write-Host "Device ID : $deviceId"

# --- Persist only the hash, via Azure AD data-plane auth (no storage key used). ---
$entity = @(
    "PartitionKey=device"
    "RowKey=$deviceId"
    "DeviceName=$DeviceName"
    "TokenHash=$tokenHash"
    "Enabled=true"
    "CreatedAtUtc=$createdAtUtc"
)

Write-Host "Writing device record (hash only) to table '$TableName' in storage account '$StorageAccountName'..."

az storage entity insert `
    --auth-mode login `
    --account-name $StorageAccountName `
    --table-name $TableName `
    --entity @entity `
    --if-exists fail `
    --output none

if ($LASTEXITCODE -ne 0) {
    Write-Error 'Failed to write the device record. Confirm the table exists (created by infra/main.bicep) and that you hold the Storage Table Data Contributor role on the storage account.'
    exit 1
}

Write-Host "`nDevice record created." -ForegroundColor Green
Write-Host "`n==================== DEVICE CREDENTIALS (shown once) ====================" -ForegroundColor Yellow
Write-Host "HAP_DEVICE_ID=$deviceId"
Write-Host "HAP_DEVICE_TOKEN=$deviceToken"
Write-Host "===========================================================================" -ForegroundColor Yellow
Write-Host "Copy these lines into the Pi's /etc/home-assistant-pi/config.env now." -ForegroundColor Yellow
Write-Host "This token is never stored in plaintext server-side; only its hash is kept. There is no way to retrieve it again -- re-run this script to issue a new credential if it is lost." -ForegroundColor Yellow

if ($OutputFile) {
    $envContent = @"
# Generated by infra/scripts/provision-device.ps1 on $createdAtUtc
# SECURITY: This file contains a plaintext device credential.
# Copy its contents to the Pi's /etc/home-assistant-pi/config.env, then
# delete this local file. Never commit this file to source control.
HAP_DEVICE_ID=$deviceId
HAP_DEVICE_TOKEN=$deviceToken
"@
    Set-Content -Path $OutputFile -Value $envContent -NoNewline:$false -Encoding utf8

    if ($IsWindows -or $env:OS -match 'Windows') {
        icacls $OutputFile /inheritance:r /grant:r "$($env:USERNAME):(R,W)" | Out-Null
    }
    else {
        chmod 600 $OutputFile
    }

    Write-Host "`nCredential also written to: $OutputFile (owner-only permissions)." -ForegroundColor Yellow
    Write-Host 'Delete this file from this machine once it has been securely transferred to the Pi.' -ForegroundColor Yellow
}
