#!/usr/bin/env bash
# build-release.sh - Build the pi-client wheel, sdist, and a lightweight
# Raspberry Pi release bundle, with SHA-256 checksums for all three.
#
# Usage:
#   pi-client/packaging/build-release.sh [--version X.Y.Z] [--output-dir DIR] [--skip-tests]
#
# --version, when given, must exactly match the package version reported by
# home_assistant_pi.version.__version__; this lets CI pass the version it
# derived from a release tag and have this script fail loudly on any
# mismatch instead of silently building the wrong artifact.
#
# By default, output is written under <repo-root>/.test-artifacts/pi-client-release
# so that local builds never scatter files across the repository. CI
# workflows may pass --output-dir to write directly into a workflow
# artifact/staging directory instead.
#
# The resulting bundle contains ONLY: the wheel, install.sh, update.sh,
# uninstall.sh, the systemd unit, a Pi-specific env example, runtime
# dependency metadata, and small bundled notification sounds (already
# inside the wheel). It never contains azure-backend, infra, git history,
# dev dependencies, or test recordings.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PI_CLIENT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${PI_CLIENT_DIR}/.." && pwd)"

OUTPUT_DIR="${REPO_ROOT}/.test-artifacts/pi-client-release"
SKIP_TESTS=false
EXPECTED_VERSION=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      EXPECTED_VERSION="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --skip-tests)
      SKIP_TESTS=true
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--version X.Y.Z] [--output-dir DIR] [--skip-tests]"
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

info() { echo "[build-release] $*"; }
err() { echo "ERROR: $*" >&2; exit 1; }

VERSION="$(
  python3 -c \
    "import runpy, sys; print(runpy.run_path(sys.argv[1])['__version__'])" \
    "${PI_CLIENT_DIR}/src/home_assistant_pi/version.py"
)"

if [[ -n "${EXPECTED_VERSION}" && "${EXPECTED_VERSION}" != "${VERSION}" ]]; then
  err "Requested --version ${EXPECTED_VERSION} does not match package version ${VERSION} (src/home_assistant_pi/version.py). Update version.py or pass the matching --version."
fi

info "Building home-assistant-pi ${VERSION}"

# 1. Run pi-client unit tests.
if [[ "${SKIP_TESTS}" != "true" ]]; then
  info "Running unit tests"
  (cd "${PI_CLIENT_DIR}" && python3 -m pytest tests) || err "Unit tests failed; aborting release build."
else
  info "Skipping unit tests (--skip-tests)"
fi

rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/dist" "${OUTPUT_DIR}/bundle-staging"

# 2/3. Build the wheel and source distribution for development use.
# Build from a disposable copy so setuptools metadata never leaks into
# pi-client/src. Everything generated by the build stays under OUTPUT_DIR.
BUILD_SOURCE="${OUTPUT_DIR}/build-source"
mkdir -p "${BUILD_SOURCE}"
cp "${PI_CLIENT_DIR}/pyproject.toml" "${PI_CLIENT_DIR}/README.md" "${BUILD_SOURCE}/"
cp -a "${PI_CLIENT_DIR}/src" "${BUILD_SOURCE}/"
info "Building wheel and sdist"
python3 -m build --wheel --sdist --outdir "${OUTPUT_DIR}/dist" "${BUILD_SOURCE}" \
  || err "Failed to build wheel/sdist."
rm -rf "${BUILD_SOURCE}"

WHEEL_FILE="$(find "${OUTPUT_DIR}/dist" -maxdepth 1 -name '*.whl' | head -n 1)"
SDIST_FILE="$(find "${OUTPUT_DIR}/dist" -maxdepth 1 -name '*.tar.gz' | head -n 1)"
[[ -n "${WHEEL_FILE}" ]] || err "Wheel build did not produce a .whl file."
[[ -n "${SDIST_FILE}" ]] || err "Sdist build did not produce a .tar.gz file."

# 4. Build the lightweight Pi release bundle (wheel + install scripts +
# systemd unit + env example + runtime dependency metadata only).
BUNDLE_STAGE="${OUTPUT_DIR}/bundle-staging"
cp "${WHEEL_FILE}" "${BUNDLE_STAGE}/"
cp "${PI_CLIENT_DIR}/scripts/install.sh" "${BUNDLE_STAGE}/"
cp "${PI_CLIENT_DIR}/scripts/update.sh" "${BUNDLE_STAGE}/"
cp "${PI_CLIENT_DIR}/scripts/uninstall.sh" "${BUNDLE_STAGE}/"
cp "${PI_CLIENT_DIR}/systemd/home-assistant.service" "${BUNDLE_STAGE}/"
cp "${PI_CLIENT_DIR}/.env.example" "${BUNDLE_STAGE}/config.env.example"
cp "${PI_CLIENT_DIR}/requirements-runtime.txt" "${BUNDLE_STAGE}/"
chmod +x "${BUNDLE_STAGE}"/*.sh

cat > "${BUNDLE_STAGE}/VERSION" <<EOF
${VERSION}
EOF

WHEEL_BASENAME="$(basename "${WHEEL_FILE}")"
WHEEL_SHA256="$(sha256sum "${BUNDLE_STAGE}/${WHEEL_BASENAME}" | cut -d ' ' -f 1)"

# The manifest lists itself among the bundle's files (it is part of the
# archive being described) and records the wheel's SHA-256 so install.sh /
# update.sh can independently verify wheel integrity without relying solely
# on the top-level SHA256SUMS file (which covers the outer artifacts: the
# wheel, sdist, and bundle archive themselves, not the bundle's contents).
cat > "${BUNDLE_STAGE}/release-manifest.json" <<EOF
{
  "name": "home-assistant-pi",
  "version": "${VERSION}",
  "wheel": "${WHEEL_BASENAME}",
  "wheelSha256": "${WHEEL_SHA256}",
  "files": [
    "${WHEEL_BASENAME}",
    "install.sh",
    "update.sh",
    "uninstall.sh",
    "home-assistant.service",
    "config.env.example",
    "requirements-runtime.txt",
    "VERSION",
    "release-manifest.json"
  ]
}
EOF

BUNDLE_FILE="${OUTPUT_DIR}/dist/home-assistant-pi-bundle-${VERSION}.tar.gz"
info "Creating bundle archive $(basename "${BUNDLE_FILE}")"
python3 "${SCRIPT_DIR}/create-release-archive.py" "${BUNDLE_STAGE}" "${BUNDLE_FILE}" \
  || err "Failed to create bundle archive."

# 5. Generate SHA-256 checksums for all release files.
info "Generating SHA256SUMS"
(
  cd "${OUTPUT_DIR}/dist"
  sha256sum "$(basename "${WHEEL_FILE}")" "$(basename "${SDIST_FILE}")" "$(basename "${BUNDLE_FILE}")" > SHA256SUMS
)

rm -rf "${BUNDLE_STAGE}"

info "Release artifacts written to ${OUTPUT_DIR}/dist:"
ls -la "${OUTPUT_DIR}/dist"
