# build-release.ps1 - Build the pi-client wheel, sdist, and a lightweight
# Raspberry Pi release bundle, with SHA-256 checksums for all three.
#
# Usage:
#   pi-client/packaging/build-release.ps1 [-Version X.Y.Z] [-OutputDir <dir>] [-SkipTests]
#
# -Version, when given, must exactly match the package version reported by
# home_assistant_pi.version.__version__; this mirrors build-release.sh's
# --version check so the requested release version and actual package version
# can never silently drift apart.
#
# By default, output is written under <source-root>/.test-artifacts/pi-client-release
# so that local builds never scatter files across the source tree.
#
# The resulting bundle contains ONLY: the wheel, install.sh, update.sh,
# uninstall.sh, the systemd unit, a Pi-specific env example, runtime
# dependency metadata, and small bundled notification sounds (already
# inside the wheel). It never contains azure-backend, infra, git history,
# dev dependencies, or test recordings.

[CmdletBinding()]
param(
    [string]$Version,
    [string]$OutputDir,
    [switch]$SkipTests
)

$ErrorActionPreference = "Stop"
$env:PYTHONDONTWRITEBYTECODE = "1"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$PiClientDir = Resolve-Path (Join-Path $ScriptDir "..")
$SourceRoot = Resolve-Path (Join-Path $PiClientDir "..")

if (-not $OutputDir) {
    $OutputDir = Join-Path $SourceRoot ".test-artifacts\pi-client-release"
}
$OutputDir = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputDir)

function Info($msg) { Write-Host "[build-release] $msg" }
function Fail($msg) { Write-Error $msg; exit 1 }

$packageVersion = python -c "import sys; sys.path.insert(0, r'$PiClientDir\src'); from home_assistant_pi.version import __version__; print(__version__)"
if (-not $packageVersion) { Fail "Could not determine package version." }

# NOTE: the local variable is deliberately NOT named `$version` -- PowerShell
# variable names are case-insensitive, so `$version` and the `-Version`
# parameter (`$Version`) would silently collide and overwrite one another,
# making this equality check always trivially true no matter what -Version
# the caller passed.
if ($Version -and $Version -ne $packageVersion) {
    Fail "Requested -Version $Version does not match package version $packageVersion (src/home_assistant_pi/version.py). Update version.py or pass the matching -Version."
}

Info "Building home-assistant-pi $packageVersion"

if (-not $SkipTests) {
    Info "Running unit tests"
    Push-Location $PiClientDir
    try {
        python -m pytest tests
        if ($LASTEXITCODE -ne 0) { Fail "Unit tests failed; aborting release build." }
    } finally {
        Pop-Location
    }
} else {
    Info "Skipping unit tests (-SkipTests)"
}

if (Test-Path $OutputDir) { Remove-Item -Recurse -Force $OutputDir }
New-Item -ItemType Directory -Force -Path (Join-Path $OutputDir "dist") | Out-Null
$bundleStage = Join-Path $OutputDir "bundle-staging"
New-Item -ItemType Directory -Force -Path $bundleStage | Out-Null

# Build from a disposable copy so setuptools metadata never leaks into
# pi-client\src. Everything generated by the build stays under OutputDir.
$buildSource = Join-Path $OutputDir "build-source"
New-Item -ItemType Directory -Force -Path $buildSource | Out-Null
Copy-Item (Join-Path $PiClientDir "pyproject.toml") $buildSource
Copy-Item (Join-Path $PiClientDir "README.md") $buildSource
Copy-Item (Join-Path $PiClientDir "src") $buildSource -Recurse

Info "Building wheel and sdist"
python -m build --wheel --sdist --outdir (Join-Path $OutputDir "dist") $buildSource
if ($LASTEXITCODE -ne 0) { Fail "Failed to build wheel/sdist." }
Remove-Item -Recurse -Force $buildSource

$distDir = Join-Path $OutputDir "dist"
$wheelFile = Get-ChildItem -Path $distDir -Filter "*.whl" | Select-Object -First 1
$sdistFile = Get-ChildItem -Path $distDir -Filter "*.tar.gz" | Select-Object -First 1
if (-not $wheelFile) { Fail "Wheel build did not produce a .whl file." }
if (-not $sdistFile) { Fail "Sdist build did not produce a .tar.gz file." }

Copy-Item $wheelFile.FullName $bundleStage
Copy-Item (Join-Path $PiClientDir "scripts\install.sh") $bundleStage
Copy-Item (Join-Path $PiClientDir "scripts\update.sh") $bundleStage
Copy-Item (Join-Path $PiClientDir "scripts\uninstall.sh") $bundleStage
Copy-Item (Join-Path $PiClientDir "systemd\home-assistant.service") $bundleStage
Copy-Item (Join-Path $PiClientDir ".env.example") (Join-Path $bundleStage "config.env.example")
Copy-Item (Join-Path $PiClientDir "requirements-runtime.txt") $bundleStage

Set-Content -Path (Join-Path $bundleStage "VERSION") -Value $packageVersion -NoNewline

$wheelHash = (Get-FileHash -Algorithm SHA256 -Path (Join-Path $bundleStage $wheelFile.Name)).Hash.ToLower()

# The manifest lists itself among the bundle's files (it is part of the
# archive being described) and records the wheel's SHA-256 so install.sh /
# update.sh can independently verify wheel integrity without relying solely
# on the top-level SHA256SUMS file (which covers the outer artifacts: the
# wheel, sdist, and bundle archive themselves, not the bundle's contents).
$manifest = @{
    name       = "home-assistant-pi"
    version    = $packageVersion
    wheel      = $wheelFile.Name
    wheelSha256 = $wheelHash
    files   = @(
        $wheelFile.Name,
        "install.sh",
        "update.sh",
        "uninstall.sh",
        "home-assistant.service",
        "config.env.example",
        "requirements-runtime.txt",
        "VERSION",
        "release-manifest.json"
    )
} | ConvertTo-Json -Depth 3
Set-Content -Path (Join-Path $bundleStage "release-manifest.json") -Value $manifest

$bundleFile = Join-Path $distDir "home-assistant-pi-bundle-$packageVersion.tar.gz"
Info "Creating bundle archive $(Split-Path -Leaf $bundleFile)"

# Normalize POSIX modes explicitly because Windows filesystems do not carry
# the executable bits that install.sh/update.sh need after extraction on a Pi.
python (Join-Path $ScriptDir "create-release-archive.py") $bundleStage $bundleFile
if ($LASTEXITCODE -ne 0) { Fail "Failed to create bundle archive." }

Info "Generating SHA256SUMS"
Push-Location $distDir
try {
    $files = @($wheelFile.Name, $sdistFile.Name, (Split-Path -Leaf $bundleFile))
    $lines = foreach ($f in $files) {
        $hash = (Get-FileHash -Algorithm SHA256 -Path $f).Hash.ToLower()
        "$hash  $f"
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText(
        (Join-Path (Get-Location) "SHA256SUMS"),
        (($lines -join "`n") + "`n"),
        $utf8NoBom
    )
} finally {
    Pop-Location
}

Remove-Item -Recurse -Force $bundleStage

Info "Release artifacts written to $distDir :"
Get-ChildItem $distDir | Format-Table Name, Length
